## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('mih', ['network', 'applications'])
    obj.source = [
        'model/mih-net-device.cc',
        'helper/mih-helper.cc',
        ]
    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'mih'
    headers.source = [
        'model/mih-net-device.h',
        'helper/mih-helper.h',
        ]

    
    bld.ns3_python_bindings()
